### ISSUE TITLE
Error when launching a scene with a TS Script `E 0:00:00:0352   _EDITOR_DEF: EditorSettings not instantiated yet`

### ISSUE THREAD

**Issue by maikkundev** [godotjs/GodotJS#8] opened 2024-09-13 10:31 UTC
- OS: MacOS 14.6.1
- Godot Version: 4.3
- GodotJS Commit: daad15100ee740209f1fb5bc529d4bce95a58874

Whenever I try to launch a scene with a TS script, the game window instantly crashes and the following errors show up under `Debugger > Errors`

```
W 0:00:00:0352   init_settings: [jsb][Warning] EditorSettings is not available for jsb::internal::Settings
  <C++ Source>   modules/GodotJS/internal/jsb_settings.cpp:47 @ init_settings()
E 0:00:00:0352   _EDITOR_DEF: EditorSettings not instantiated yet.
  <C++ Error>    Parameter "EditorSettings::get_singleton()" is null.
  <C++ Source>   editor/editor_settings.cpp:1271 @ _EDITOR_DEF()
E 0:00:00:0352   _EDITOR_DEF: EditorSettings not instantiated yet.
  <C++ Error>    Parameter "EditorSettings::get_singleton()" is null.
  <C++ Source>   editor/editor_settings.cpp:1271 @ _EDITOR_DEF()
```

The script I'm trying to execute:
```ts
import { Area2D, CharacterBody2D, float64, Node2D, Vector2 } from "godot";
import * as jsb from "godot-jsb";

const MAX_SPEED = 300;

export default class BasicEnemy extends CharacterBody2D {
  _ready(): void {
    let area2Node = this.get_node("BasicEnemy/Area2D") as Area2D;
    area2Node.area_entered.connect(jsb.callable(this, this.on_area_entered), 0);
  }

  _process(delta: float64): void {
    let direction: Vector2 = this.get_direction_to_player();
    this.velocity = new Vector2(
      direction.x * MAX_SPEED,
      direction.y * MAX_SPEED
    );
    this.move_and_slide();
  }

  get_direction_to_player(): Vector2 {
    let player_node: Node2D = this.get_tree().get_first_node_in_group(
      "player"
    ) as Node2D;
    if (player_node != null) {
      return new Vector2(
        player_node.global_position.x - this.global_position.x,
        player_node.global_position.y - this.global_position.y
      ).normalized();
    }
    return Vector2.ZERO;
  }

  on_area_entered(other_area: Area2D) {
    this.queue_free();
  }
}

```

**Comment by ialex32x** [comment] 2024-09-13 13:02
It's caused by `EditorHelp::get_doc_data()` returning null in play mode. Fixed on the `main` branch now. BTW, to trace crash issues of the game instance started from the editor, directly launching from the IDE with arguments `--path "path/to/project" res://scene_name.tscn` help :)

**Comment by maikkundev** [comment] 2024-09-13 13:34
> It's caused by `EditorHelp::get_doc_data()` returning null in play mode. Fixed on the `main` branch now. BTW, to trace crash issues of the game instance started from the editor, directly launching from the IDE with arguments `--path "path/to/project" res://scene_name.tscn` help :)

Will build and test soon

**Comment by maikkundev** [comment] 2024-09-13 20:42
the errors seem to have been fixed, still getting this warning tho:
`W 0:00:00:0366   init_settings: [jsb][Warning] EditorSettings is not available for jsb::internal::Settings
  <C++ Source>   modules/GodotJS/internal/jsb_settings.cpp:47 @ init_settings()`

**Comment by ialex32x** [comment] 2024-09-13 22:11
> the errors seem to have been fixed, still getting this warning tho: `W 0:00:00:0366 init_settings: [jsb][Warning] EditorSettings is not available for jsb::internal::Settings <C++ Source> modules/GodotJS/internal/jsb_settings.cpp:47 @ init_settings()`

Will remove this warning later in play mode. Currently, it can be safely ignored.

**Closed** 2024-10-08 08:25 UTC
Labels: bug
